title: Testium
baseurl: ''
sourceUrl: https://github.com/testiumjs/testiumjs.github.io
sourceBranch: master
projectUrl: https://github.com/groupon/testium
copyright: "Copyright © 2015 Groupon, Inc. All Rights Reserved."

exclude:
- README.md
- Gemfile
- Gemfile.lock

markdown: redcarpet
sass:
  style: :compressed
defaults:
  - scope:
      path: ""
    values:
      category: docs

redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - with_toc_data
